---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: siseg/siseg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 2000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app: flaskapi
  type: LoadBalancer
